// <auto-generated />
using System;
using DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataContext.Migrations
{
    [DbContext(typeof(Database))]
    partial class DatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Repository.Entities.ChatMessage", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageID"));

                    b.Property<int?>("ChatSessionSessionID")
                        .HasColumnType("int");

                    b.Property<int>("IDCustomer")
                        .HasColumnType("int");

                    b.Property<int>("IDRepresentative")
                        .HasColumnType("int");

                    b.Property<int>("IDSend")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StatusMessage")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageID");

                    b.HasIndex("ChatSessionSessionID");

                    b.HasIndex("IDCustomer");

                    b.HasIndex("IDRepresentative");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Repository.Entities.ChatSession", b =>
                {
                    b.Property<int>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionID"));

                    b.Property<bool>("ChatStatus")
                        .HasColumnType("bit");

                    b.Property<int>("CustomerIDCustomers")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDCustomer")
                        .HasColumnType("int");

                    b.Property<int>("IDRepresentative")
                        .HasColumnType("int");

                    b.Property<int>("RepresentativeIDRepresentative")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SessionID");

                    b.HasIndex("CustomerIDCustomers");

                    b.HasIndex("RepresentativeIDRepresentative");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("Repository.Entities.Customer", b =>
                {
                    b.Property<int>("IDCustomers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDCustomers"));

                    b.Property<string>("EmailCust")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameCust")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordCust")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StatusCust")
                        .HasColumnType("bit");

                    b.HasKey("IDCustomers");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Repository.Entities.Representative", b =>
                {
                    b.Property<int>("IDRepresentative")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDRepresentative"));

                    b.Property<string>("EmailRepr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameRepr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordRepr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScoreForMonth")
                        .HasColumnType("int");

                    b.Property<bool>("StatusRepr")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("entryHourRepr")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("exitHourRepr")
                        .HasColumnType("time");

                    b.HasKey("IDRepresentative");

                    b.ToTable("Representatives");
                });

            modelBuilder.Entity("Repository.Entities.Topic", b =>
                {
                    b.Property<int>("IDTopics")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDTopics"));

                    b.Property<double>("AverageTreatTime")
                        .HasColumnType("float");

                    b.Property<string>("NameTopic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StatusTopic")
                        .HasColumnType("bit");

                    b.Property<int>("priorityTopics")
                        .HasColumnType("int");

                    b.HasKey("IDTopics");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("Repository.Entities.ChatMessage", b =>
                {
                    b.HasOne("Repository.Entities.ChatSession", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatSessionSessionID");

                    b.HasOne("Repository.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("IDCustomer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Representative", "Representative")
                        .WithMany()
                        .HasForeignKey("IDRepresentative")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Representative");
                });

            modelBuilder.Entity("Repository.Entities.ChatSession", b =>
                {
                    b.HasOne("Repository.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerIDCustomers")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Representative", "Representative")
                        .WithMany()
                        .HasForeignKey("RepresentativeIDRepresentative")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Representative");
                });

            modelBuilder.Entity("Repository.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
